name: Cross-Platform Build

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            runner: ubuntu-22.04
          - goos: linux
            goarch: arm64
            runner: ubuntu-22.04
          - goos: windows
            goarch: amd64
            runner: windows-2022
          - goos: windows
            goarch: arm64
            runner: windows-2022
          - goos: darwin
            goarch: arm64
            runner: macos-14
    runs-on: ${{ matrix.runner }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Обновлено до v4

      - name: Set up Go
        uses: actions/setup-go@v5  # Обновлено до v5
        with:
          go-version: '1.22.x'    # Используем версию из go.mod с возможностью патчей
          cache: true             # Включаем кэширование зависимостей

      - name: Install dependencies
        run: go mod download

      - name: Build for ${{ matrix.goos }}-${{ matrix.goarch }}
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          go build -v -trimpath -ldflags "-w -s" -o rocket-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd/main

      - name: Test
        run: go test -v ./...

      - name: Archive binary
        uses: actions/upload-artifact@v4
        with:
          name: rocket-${{ matrix.goos }}-${{ matrix.goarch }}
          path: rocket-${{ matrix.goos }}-${{ matrix.goarch }}
          retention-days: 7       # Добавлено ограничение хранения артефактов
